"""add user_id column in notes table

Revision ID: 31273f7f8191
Revises: 2350de13ab93
Create Date: 2025-10-26 14:52:16.792575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31273f7f8191'
down_revision: Union[str, Sequence[str], None] = '2350de13ab93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'notes', ['id'])
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###
